# Generated by Django 4.2 on 2024-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apptheme',
            old_name='header_background',
            new_name='primary',
        ),
        migrations.AddField(
            model_name='apptheme',
            name='secondary',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
